version: '3.8'

services:
  user-profile-management-bff:
    build:
      context: ./user-profile-management-bff
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - profile-app-service

  profile-app-service:
    build:
      context: ./profile-app-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydatabase
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: